:set number
:set relativenumber
:set scrolloff=999
:set ignorecase
:set smartcase

:set completeopt-=preview " For No Previews
syntax on
filetype on

nnoremap <SPACE> <Nop>
let mapleader = " "
inoremap jk <Esc>

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall
endif

call plug#begin('~/.vim/plugged')
	source ~/dotfiles/vim/plugins-base.vim
call plug#end()

map <Leader> <Plug>(easymotion-prefix)

nnoremap <C-f> :NERDTreeFocus<CR>
nnoremap <C-n> :NERDTree<CR>
nnoremap <C-t> :NERDTreeToggle<CR>

nmap <F8> :TagbarToggle<CR>

if has('nvim')
	" Find files using Telescope command-line sugar.
	nnoremap <leader><leader>ff <cmd>Telescope find_files<cr>
	nnoremap <leader><leader>fg <cmd>Telescope live_grep<cr>
	nnoremap <leader><leader>fb <cmd>Telescope buffers<cr>
	nnoremap <leader><leader>fh <cmd>Telescope help_tags<cr>
endif
